CREATE TABLE Facultad(
	ID_FACULTAD SERIAL PRIMARY KEY NOT NULL,
	Nombre VARCHAR(300) NOT NULL
);

CREATE TABLE Carrera(
	ID_CARRERA SERIAL PRIMARY KEY NOT NULL,
	Nombre VARCHAR(300) NOT NULL
);
CREATE TABLE Estudiante(
	ID_ESTUDIANTE SERIAL PRIMARY KEY NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	CC VARCHAR(10)
);

CREATE TABLE ASIGNATURA(
	ID_ASIGNATURA SERIAL PRIMARY KEY NOT NULL,
	Nombre VARCHAR(50),
	Semestre VARCHAR(100)
);
INSERT INTO uce.asignatura(nombre,semestre) 
	VALUES('Introducción a la matemática', 'primero')*/

SELECT version()

SELECT * FROM uce.asignatura;
